set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN Y16 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN Y17 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN R14 [get_ports {LEDs[0]}]
