# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/TUTORIAL/FPGA/fpga-saghafi/Digital_design/08/BLINK_Z00/BLINK_Z00.srcs/sources_1/bd/BLINK_Z0_Block/ip/BLINK_Z0_Block_processing_system7_0_0/BLINK_Z0_Block_processing_system7_0_0.xci
# IP: The module: 'BLINK_Z0_Block_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/TUTORIAL/FPGA/fpga-saghafi/Digital_design/08/BLINK_Z00/BLINK_Z00.srcs/sources_1/bd/BLINK_Z0_Block/ip/BLINK_Z0_Block_processing_system7_0_0/BLINK_Z0_Block_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BLINK_Z0_Block_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/TUTORIAL/FPGA/fpga-saghafi/Digital_design/08/BLINK_Z00/BLINK_Z00.srcs/sources_1/bd/BLINK_Z0_Block/ip/BLINK_Z0_Block_processing_system7_0_0/BLINK_Z0_Block_processing_system7_0_0.xci
# IP: The module: 'BLINK_Z0_Block_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/TUTORIAL/FPGA/fpga-saghafi/Digital_design/08/BLINK_Z00/BLINK_Z00.srcs/sources_1/bd/BLINK_Z0_Block/ip/BLINK_Z0_Block_processing_system7_0_0/BLINK_Z0_Block_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BLINK_Z0_Block_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
