set_property SRC_FILE_INFO {cfile:F:/TUTORIAL/FPGA/fpga-saghafi/Digital_design/08/BLINK_Z00/BLINK_Z00.srcs/constrs_1/new/pinout_blink.xdc rfile:../../../BLINK_Z00.srcs/constrs_1/new/pinout_blink.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {LEDs[2]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {LEDs[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports {LEDs[0]}]
