# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout_blink.xdc

# Block Designs: bd/BLINK_Z0_Block/BLINK_Z0_Block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLINK_Z0_Block || ORIG_REF_NAME==BLINK_Z0_Block} -quiet] -quiet

# IP: bd/BLINK_Z0_Block/ip/BLINK_Z0_Block_processing_system7_0_0/BLINK_Z0_Block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLINK_Z0_Block_processing_system7_0_0 || ORIG_REF_NAME==BLINK_Z0_Block_processing_system7_0_0} -quiet] -quiet

# IP: bd/BLINK_Z0_Block/ip/BLINK_Z0_Block_BLINK_Z00_0_0/BLINK_Z0_Block_BLINK_Z00_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLINK_Z0_Block_BLINK_Z00_0_0 || ORIG_REF_NAME==BLINK_Z0_Block_BLINK_Z00_0_0} -quiet] -quiet

# XDC: bd/BLINK_Z0_Block/BLINK_Z0_Block_ooc.xdc
